### ISSUE TITLE
Get current version from package.json

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#310]
Currently, we manually update the version string in the cli when I remember https://github.com/doug-wade/tybalt/pull/296/files#diff-fde3c020439d16b612facc24e7dc713eb3db8482b286e2cc787a5cae8fdc5367R10

This makes the version string less effective for users, since it may be out-of-date. Instead, let's parse package.json and get the version field.

**Comment by Ashvith10** [comment]
@doug-wade could you assign this to @givtaj ? It makes searching for unassigned issues a lot easier :smile_cat: .

**Comment by doug-wade** [comment]
@Ashvith10 I don't think so -- I think they would have to participate in the issue for me to be able to assign them. I'm not 💯 about that, it's just they don't appear in the combo box.

Also, they haven't responded to the pr feedback yet, so if you have a changeset where the tests pass, I'd certainly take it.
