### ISSUE TITLE
Something is wrong with our dns

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#356]
Every time we deploy, I have to re-set the custom domains on settings > pages, which it doesn't seem like I should have to do. Maybe we need a CNAME file?

**Comment by doug-wade** [comment]
The CNAME does not seem to have helped

**Comment by doug-wade** [comment]
When we're having an outage, there is no CNAME file on the gh-pages branch, and updating the field adds one

**Comment by ysfchn** [comment]
Just came across this issue from Mastodon, and thought I could help!

I guess that `peaceiris/actions-gh-pages` GitHub Action clears out the `gh-pages` branch completely before starting to deploy, so I guess it won't matter if you manually add CNAME here, as it will be deleted again in the next deploy.

Instead, you should create/generate a CNAME file in the output directory (`publish_dir`), in this case `./packages/website/_site`, so all files including the CNAME file itself will be committed to `gh-pages` in the next deploy.
```
publish_dir: ./packages/website/_site
```

Alternatively, [there is a `cname` option in the action](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname).
```
cname: www.tybalt.org
```

You can also check the other configuration options of the action, such as excluding specific files to prevent the action from deleting CNAME.

Hope this helps!

**Comment by doug-wade** [comment]
Thanks for stopping by @ysfchn -- I tried that and just had my first clean deploy! Thanks so much!
