### ISSUE TITLE
Link to bug tracker and repository in package.json

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#364]
Socket.dev is lowering our score because our package.json is missing some of the links they expect: the website, the issue tracker, and the repository. Let's go through all our package.jsons and add the required fields.

**Comment by doug-wade** [comment]
I marked this a good first issue, so to make it a little easier, here's the docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-json

And I think we need to add the following three keys to every file called package.json in the monorepo: 

```json
{
    "bugs": { "url" : "https://github.com/doug-wade/tybalt/issues" },
    "homepage": "https://tybalt.org",
    "repository": {
        "type": "git",
        "url": "https://github.com/doug-wade/tybalt.git"
     }
}
```

**Comment by Ashvith10** [comment]
@doug-wade about the repository, should the repository link for packages in workspace point to the main git repo, or the link to the topmost file? (https://github.com/doug-wade/tybalt.git vs https://github.com/doug-wade/tybalt/tree/master/packages/cli)?

**Comment by doug-wade** [comment]
My understanding is that we should like to the main git repo in the `url` (iiuc, the url is to a git repository, so something that can be cloned, and the packages subdirectories can't be cloned) and we should specify the directory in `directory`

**Comment by Ashvith10** [comment]
There are a few missing pages and labels.

Missing labels are:
- eleventy-plugin-vanilla-example
- esbuild-plugin
- test-utils-lit-example

Missing documentations are:
- eleventy-plugin-vanilla-example
- example
- test-utils-lit-example
- website

What should be done with these?
