### ISSUE TITLE
Guide names have dashes in their titles

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#405]
<img width="294" alt="Screenshot 2023-08-12 at 8 32 48 AM" src="https://github.com/doug-wade/tybalt/assets/3477707/4fb6698f-d150-4076-9cb7-f9f8948b6ab7">

**Comment by doug-wade** [comment]
We need to add a `.replace('-', ' ')` to `guide` at this line: https://github.com/doug-wade/tybalt/blob/2e2e882d454e31d1a8d859c7a264c68060d37434/packages/website/components/sidebar.js#L20

**Comment by Ashvith10** [comment]
@doug-wade personal opinion, but I think we should remove the preceding "guide" as well, as it is redundant. Could you assign this to me btw?
