### ISSUE TITLE
Website doesn't have a meta description

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#409]
I ran the Chrome lighthouse report, and it gave me an SEO error:

> Meta descriptions may be included in search results to concisely summarize page content. [Learn more about the meta description](https://developer.chrome.com/docs/lighthouse/seo/meta-description/?utm_source=lighthouse&utm_medium=devtools).

<img width="797" alt="This is a screenshot of the issue quoted above" src="https://github.com/doug-wade/tybalt/assets/3477707/ee3c691a-4379-491b-ad1b-8100721add86">

**Comment by doug-wade** [comment]
We'll need to add the new attribute right here: https://github.com/doug-wade/tybalt/blob/master/packages/website/index.html#L2

**Comment by doug-wade** [comment]
Looks like our first try at this didn't work because we used the fancy double-quotes

<img width="619" alt="Screenshot 2023-08-12 at 9 07 15 PM" src="https://github.com/doug-wade/tybalt/assets/3477707/f47bc0db-7595-47ad-bbe7-a3b1e0fb6a7c">

**Comment by conorvenus** [comment]
Oh that's my bad! 😄 

I am pretty sure I just copied it off the Lighthouse reference link and changed the description, strange why it used a different Unicode character for the double quotes. 🤔 

Thanks for the second fix.
